#!/usr/bin/env node

'use strict';
const app = require('../index');
const http = require('http');

const PORT = process.env.PORT || 3000;
const server = http.createServer(app);

server.listen(PORT, () => {
  console.log(`Listening : ${PORT}`);
});